# Generated by Django 2.1.7 on 2019-04-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiReader', '0003_auto_20190222_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_detector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('detector', models.CharField(max_length=100)),
                ('calcAmount', models.IntegerField(default=0)),
                ('reliabValue', models.IntegerField(default=0)),
            ],
        ),
    ]
